
name: Docker Docs Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/build_docs.sh"
      - ".github/dockerfile"
      - "docs/requirements.txt"
jobs:
  base_docs_image:
    name: Create documenatation Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sdpphy-docs-image:latest
