name: Documentation
on:
  push:
    branches:
      - ganesh_dev
      - main
    paths:
      - "docs/**"
      - "examples/**"
      - "spydrnet_physical/ir/**"
      - "spydrnet_physical/util/**"
      - "spydrnet_physical/support_files/sample_verilog/**"
      - ".github/workflows/docs.yml"

jobs:
  build_docs:
    runs-on: ubuntu-latest
    container: ghcr.io/ganeshgore/sdpphy-docs-image:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Documentation
        shell: bash
        run: |
          source /tmp/buildenv/bin/activate
          if [ -f "requirements.txt" ]; then
            python3 -m pip install --upgrade \
            --no-cache-dir -r requirements.txt
          fi
          if [ -f "docs/requirements.txt" ]; then
            python3 -m pip install --upgrade \
            --no-cache-dir -r docs/requirements.txt
          fi
          export PYTHONPATH=$PYTHONPATH:${PWD}
          cd docs && make html
          sed -i "/.*docs.*build.*/d" .gitignore
          cat .gitignore
      - name: Upload regression results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.name}}_results
          retention-days: 2
          path: |
            docs/**/*
      - name: Deploy documentation
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: docs/build/html
          destination_dir: docs/${GITHUB_REF##*/}
          exclude_assets: "doctrees"
