name: "Documentation building"
on:
  push:
    branches:
      - ganesh_dev
      - main
    paths:
      - "docs/**"
      - "examples/**"
      - "spydrnet_physical/support_files/sample_verilog/**"
      - ".github/workflows/docs.yml"

jobs:
  build_docs:
    runs-on: ubuntu-latest
    container: ghcr.io/ganeshgore/sdpphy-docs-image:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Documentation
        shell: bash
        run: |
          bash .github/build_docs.sh
          cd docs && make html
          sed -i "/.*docs.*build.*/d" .gitignore
          cat .gitignore
          ls && ls docs/*
      - name: Deploy documentation
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: docs/build/html
          destination_dir: docs/
          exclude_assets: "doctrees"